program abi;

{$APPTYPE CONSOLE}

uses
  SDL3,
  SDL3_image,
  SDL3_ttf,
  SDL3_mixer;

procedure Check(const Name: string; Actual, Expected: Integer);
begin
  if Actual <> Expected then
  begin
    WriteLn('FAIL ', Name, ' SizeOf=', Actual, ' expected=', Expected);
    Halt(1);
  end;
  WriteLn('OK   ', Name, ' SizeOf=', Actual);
end;

begin
  Check('Sint8', SizeOf(Sint8), 1);
  Check('Uint8', SizeOf(Uint8), 1);
  Check('Sint16', SizeOf(Sint16), 2);
  Check('Uint16', SizeOf(Uint16), 2);
  Check('Sint32', SizeOf(Sint32), 4);
  Check('Uint32', SizeOf(Uint32), 4);
  Check('Sint64', SizeOf(Sint64), 8);
  Check('Uint64', SizeOf(Uint64), 8);
  Check('Boolean', SizeOf(Boolean), 1);
  Check('SDL_Point', SizeOf(SDL_Point), 8);
  Check('SDL_FPoint', SizeOf(SDL_FPoint), 8);
  Check('SDL_Rect', SizeOf(SDL_Rect), 16);
  Check('SDL_FRect', SizeOf(SDL_FRect), 16);
  Check('SDL_CommonEvent', SizeOf(SDL_CommonEvent), 16);
  Check('SDL_Event', SizeOf(SDL_Event), 128);
  Check('SDL_DisplayEvent', SizeOf(SDL_DisplayEvent), 32);
  Check('SDL_WindowEvent', SizeOf(SDL_WindowEvent), 32);
  Check('SDL_QuitEvent', SizeOf(SDL_QuitEvent), 16);
  Check('SDL_UserEvent', SizeOf(SDL_UserEvent), 40);
  Check('SDL_DisplayMode', SizeOf(SDL_DisplayMode), 40);
  Check('SDL_Color', SizeOf(SDL_Color), 4);
  Check('SDL_FColor', SizeOf(SDL_FColor), 16);
  Check('SDL_Palette', SizeOf(SDL_Palette), 24);
  Check('SDL_PixelFormatDetails', SizeOf(SDL_PixelFormatDetails), 32);
  Check('SDL_Surface', SizeOf(SDL_Surface), 48);
  Check('SDL_Vertex', SizeOf(SDL_Vertex), 32);
  Check('SDL_Texture', SizeOf(SDL_Texture), 16);
  Check('SDL_CursorFrameInfo', SizeOf(SDL_CursorFrameInfo), 16);
  Check('SDL_KeyboardDeviceEvent', SizeOf(SDL_KeyboardDeviceEvent), 24);
  Check('SDL_KeyboardEvent', SizeOf(SDL_KeyboardEvent), 40);
  Check('SDL_TextEditingEvent', SizeOf(SDL_TextEditingEvent), 40);
  Check('SDL_TextEditingCandidatesEvent', SizeOf(SDL_TextEditingCandidatesEvent), 48);
  Check('SDL_TextInputEvent', SizeOf(SDL_TextInputEvent), 32);
  Check('SDL_MouseDeviceEvent', SizeOf(SDL_MouseDeviceEvent), 24);
  Check('SDL_MouseMotionEvent', SizeOf(SDL_MouseMotionEvent), 48);
  Check('SDL_MouseButtonEvent', SizeOf(SDL_MouseButtonEvent), 40);
  Check('SDL_MouseWheelEvent', SizeOf(SDL_MouseWheelEvent), 56);
  Check('SDL_GUID', SizeOf(SDL_GUID), 16);
  Check('SDL_PathInfo', SizeOf(SDL_PathInfo), 40);
  Check('SDL_Finger', SizeOf(SDL_Finger), 24);
  Check('SDL_AudioSpec', SizeOf(SDL_AudioSpec), 12);
  Check('SDL_IOStreamInterface', SizeOf(SDL_IOStreamInterface), 56);
  Check('SDL_VirtualJoystickTouchpadDesc', SizeOf(SDL_VirtualJoystickTouchpadDesc), 8);
  Check('SDL_VirtualJoystickSensorDesc', SizeOf(SDL_VirtualJoystickSensorDesc), 8);
  Check('SDL_VirtualJoystickDesc', SizeOf(SDL_VirtualJoystickDesc), 136);
  Check('SDL_GamepadBinding', SizeOf(SDL_GamepadBinding), 32);
  Check('SDL_JoyAxisEvent', SizeOf(SDL_JoyAxisEvent), 32);
  Check('SDL_JoyBallEvent', SizeOf(SDL_JoyBallEvent), 32);
  Check('SDL_JoyHatEvent', SizeOf(SDL_JoyHatEvent), 24);
  Check('SDL_JoyButtonEvent', SizeOf(SDL_JoyButtonEvent), 24);
  Check('SDL_JoyDeviceEvent', SizeOf(SDL_JoyDeviceEvent), 24);
  Check('SDL_JoyBatteryEvent', SizeOf(SDL_JoyBatteryEvent), 32);
  Check('SDL_GamepadTouchpadEvent', SizeOf(SDL_GamepadTouchpadEvent), 40);
  Check('SDL_GamepadSensorEvent', SizeOf(SDL_GamepadSensorEvent), 48);
  Check('SDL_AudioDeviceEvent', SizeOf(SDL_AudioDeviceEvent), 24);
  Check('SDL_TouchFingerEvent', SizeOf(SDL_TouchFingerEvent), 56);
  Check('SDL_PinchFingerEvent', SizeOf(SDL_PinchFingerEvent), 24);
  Check('SDL_ClipboardEvent', SizeOf(SDL_ClipboardEvent), 32);
  Check('SDL_Locale', SizeOf(SDL_Locale), 16);
  Check('SDL_DateTime', SizeOf(SDL_DateTime), 36);
  Check('SDL_AtomicInt', SizeOf(SDL_AtomicInt), 4);
  Check('SDL_AtomicU32', SizeOf(SDL_AtomicU32), 4);
  Check('SDL_InitState', SizeOf(SDL_InitState), 24);
  Check('SDL_MessageBoxButtonData', SizeOf(SDL_MessageBoxButtonData), 16);
  Check('SDL_MessageBoxColor', SizeOf(SDL_MessageBoxColor), 3);
  Check('SDL_MessageBoxColorScheme', SizeOf(SDL_MessageBoxColorScheme), 15);
  Check('SDL_MessageBoxData', SizeOf(SDL_MessageBoxData), 56);
  Check('SDL_DialogFileFilter', SizeOf(SDL_DialogFileFilter), 16);
  Check('SDL_AssertData', SizeOf(SDL_AssertData), 48);
  Check('SDL_AsyncIOOutcome', SizeOf(SDL_AsyncIOOutcome), 56);
  Check('SDL_StorageInterface', SizeOf(SDL_StorageInterface), 96);
  Check('SDL_PenProximityEvent', SizeOf(SDL_PenProximityEvent), 24);
  Check('SDL_PenMotionEvent', SizeOf(SDL_PenMotionEvent), 40);
  Check('SDL_PenTouchEvent', SizeOf(SDL_PenTouchEvent), 40);
  Check('SDL_PenButtonEvent', SizeOf(SDL_PenButtonEvent), 40);
  Check('SDL_PenAxisEvent', SizeOf(SDL_PenAxisEvent), 48);
  Check('SDL_CameraSpec', SizeOf(SDL_CameraSpec), 24);
  Check('SDL_HapticDirection', SizeOf(SDL_HapticDirection), 16);
  Check('SDL_HapticConstant', SizeOf(SDL_HapticConstant), 40);
  Check('SDL_HapticPeriodic', SizeOf(SDL_HapticPeriodic), 48);
  Check('SDL_HapticCondition', SizeOf(SDL_HapticCondition), 68);
  Check('SDL_HapticRamp', SizeOf(SDL_HapticRamp), 44);
  Check('SDL_HapticLeftRight', SizeOf(SDL_HapticLeftRight), 12);
  Check('SDL_HapticCustom', SizeOf(SDL_HapticCustom), 56);
  Check('SDL_HapticEffect', SizeOf(SDL_HapticEffect), 72);
  Check('SDL_hid_device_info', SizeOf(SDL_hid_device_info), 80);
  Check('SDL_GPUViewport', SizeOf(SDL_GPUViewport), 24);
  Check('SDL_GPUTextureTransferInfo', SizeOf(SDL_GPUTextureTransferInfo), 24);
  Check('SDL_GPUTransferBufferLocation', SizeOf(SDL_GPUTransferBufferLocation), 16);
  Check('SDL_GPUTextureLocation', SizeOf(SDL_GPUTextureLocation), 32);
  Check('SDL_GPUTextureRegion', SizeOf(SDL_GPUTextureRegion), 40);
  Check('SDL_GPUBlitRegion', SizeOf(SDL_GPUBlitRegion), 32);
  Check('SDL_GPUBufferLocation', SizeOf(SDL_GPUBufferLocation), 16);
  Check('SDL_GPUBufferRegion', SizeOf(SDL_GPUBufferRegion), 16);
  Check('SDL_GPUIndirectDrawCommand', SizeOf(SDL_GPUIndirectDrawCommand), 16);
  Check('SDL_GPUIndexedIndirectDrawCommand', SizeOf(SDL_GPUIndexedIndirectDrawCommand), 20);
  Check('SDL_GPUIndirectDispatchCommand', SizeOf(SDL_GPUIndirectDispatchCommand), 12);
  Check('SDL_GPUSamplerCreateInfo', SizeOf(SDL_GPUSamplerCreateInfo), 52);
  Check('SDL_GPUVertexBufferDescription', SizeOf(SDL_GPUVertexBufferDescription), 16);
  Check('SDL_GPUVertexAttribute', SizeOf(SDL_GPUVertexAttribute), 16);
  Check('SDL_GPUVertexInputState', SizeOf(SDL_GPUVertexInputState), 32);
  Check('SDL_GPUStencilOpState', SizeOf(SDL_GPUStencilOpState), 16);
  Check('SDL_GPUColorTargetBlendState', SizeOf(SDL_GPUColorTargetBlendState), 32);
  Check('SDL_GPUShaderCreateInfo', SizeOf(SDL_GPUShaderCreateInfo), 56);
  Check('SDL_GPUTextureCreateInfo', SizeOf(SDL_GPUTextureCreateInfo), 36);
  Check('SDL_GPUBufferCreateInfo', SizeOf(SDL_GPUBufferCreateInfo), 12);
  Check('SDL_GPUTransferBufferCreateInfo', SizeOf(SDL_GPUTransferBufferCreateInfo), 12);
  Check('SDL_GPURasterizerState', SizeOf(SDL_GPURasterizerState), 28);
  Check('SDL_GPUMultisampleState', SizeOf(SDL_GPUMultisampleState), 12);
  Check('SDL_GPUDepthStencilState', SizeOf(SDL_GPUDepthStencilState), 44);
  Check('SDL_GPUColorTargetDescription', SizeOf(SDL_GPUColorTargetDescription), 36);
  Check('SDL_GPUGraphicsPipelineTargetInfo', SizeOf(SDL_GPUGraphicsPipelineTargetInfo), 24);
  Check('SDL_GPUGraphicsPipelineCreateInfo', SizeOf(SDL_GPUGraphicsPipelineCreateInfo), 168);
  Check('SDL_GPUComputePipelineCreateInfo', SizeOf(SDL_GPUComputePipelineCreateInfo), 72);
  Check('SDL_GPUColorTargetInfo', SizeOf(SDL_GPUColorTargetInfo), 64);
  Check('SDL_GPUDepthStencilTargetInfo', SizeOf(SDL_GPUDepthStencilTargetInfo), 32);
  Check('SDL_GPUBlitInfo', SizeOf(SDL_GPUBlitInfo), 96);
  Check('SDL_GPUBufferBinding', SizeOf(SDL_GPUBufferBinding), 16);
  Check('SDL_GPUTextureSamplerBinding', SizeOf(SDL_GPUTextureSamplerBinding), 16);
  Check('SDL_GPUStorageBufferReadWriteBinding', SizeOf(SDL_GPUStorageBufferReadWriteBinding), 16);
  Check('SDL_GPUStorageTextureReadWriteBinding', SizeOf(SDL_GPUStorageTextureReadWriteBinding), 24);
  Check('SDL_GPUVulkanOptions', SizeOf(SDL_GPUVulkanOptions), 56);
  Check('SDL_GPURenderStateCreateInfo', SizeOf(SDL_GPURenderStateCreateInfo), 64);
  Check('IMG_Animation', SizeOf(IMG_Animation), 32);
  Check('TTF_Text', SizeOf(TTF_Text), 24);
  Check('TTF_SubString', SizeOf(TTF_SubString), 36);
  Check('MIX_StereoGains', SizeOf(MIX_StereoGains), 8);
  Check('MIX_Point3D', SizeOf(MIX_Point3D), 12);
  Check('TTF_GPUAtlasDrawSequence', SizeOf(TTF_GPUAtlasDrawSequence), 56);
  WriteLn('camera drivers ', SDL_GetNumCameraDrivers);
  WriteLn('All required ABI checks passed.');
end.
